/**
 * Eth
 */

 export const SET_BLOCK_HEIGHT = "SET-BLOCK-HEIGHT";

 export const SET_ACCOUNT_ADDRESS = "SET-ACCOUNT-ADDRESS";

 export const SET_MEMBERSHIP = "SET-MEMBERSHIP";

/**
 * Poll
 */

 export const SET_POLL_STATISTICS = "SET-POLL-STATISTICS";

 export const ADD_MONITORING_POLLS = "ADD-MONITORING-POLLS";

 export const REMOVE_MONITORING_POLLS = "REMOVE-MONITORING-POLLS";

 export const SET_USER_SEARCH_KEYWORDS = "SET-USER-SEARCH-KEYWORDS";

 export const SET_SEARCH_RESULTS_AMOUNT = "SET-SEARCH-RESULTS-AMOUNT";

 export const SET_ACTIVE_POLL_DETAIL = "SET-ACTIVE-POLL-DETAIL";

 export const SET_ACTIVE_POLL_DETAIL_IN_PROGRESS = "SET-ACTIVE-POLL-DETAIL-IN-PROGRESS";

/**
 * User runtime configurations
 */

 export const SET_USER_WINDOW_FOCUS_STATUS = "SET-USER-WINDOW-FOCUS-STATUS";

 export const SET_NOTIFICATION_STATUS = "SET-NOTIFICATION-STATUS";

 export const SET_SEARCH_BAR = "SET-SEARCH-BAR";
